// Generated by scripts/generate_localizations.py. Do not edit by hand.
package com.izowooi.dm

import androidx.annotation.StringRes

object TextResources {
    @StringRes fun id(key: String): Int = when (key) {
        "app_name" -> R.string.app_name
        "tagline" -> R.string.tagline
        "ready" -> R.string.ready
        "live" -> R.string.live
        "finished" -> R.string.finished
        "starting" -> R.string.starting
        "start" -> R.string.start
        "stop" -> R.string.stop
        "measure_again" -> R.string.measure_again
        "settings" -> R.string.settings
        "done" -> R.string.done
        "current_level" -> R.string.current_level
        "relative_level" -> R.string.relative_level
        "estimated_level" -> R.string.estimated_level
        "uncalibrated" -> R.string.uncalibrated
        "calibrated" -> R.string.calibrated
        "relative_hint" -> R.string.relative_hint
        "estimated_hint" -> R.string.estimated_hint
        "minimum" -> R.string.minimum
        "average" -> R.string.average
        "maximum" -> R.string.maximum
        "recent60" -> R.string.recent60
        "elapsed" -> R.string.elapsed
        "weighting" -> R.string.weighting
        "flat" -> R.string.flat
        "input" -> R.string.input
        "unknown_input" -> R.string.unknown_input
        "rms100" -> R.string.rms100
        "calibration" -> R.string.calibration
        "calibration_intro" -> R.string.calibration_intro
        "profiles" -> R.string.profiles
        "none" -> R.string.none
        "create_profile" -> R.string.create_profile
        "profile_name" -> R.string.profile_name
        "reference_db" -> R.string.reference_db
        "notes" -> R.string.notes
        "reference_agreement" -> R.string.reference_agreement
        "stable_required" -> R.string.stable_required
        "save_profile" -> R.string.save_profile
        "delete_profile" -> R.string.delete_profile
        "reset" -> R.string.reset
        "calibration_mismatch" -> R.string.calibration_mismatch
        "summary" -> R.string.summary
        "share" -> R.string.share
        "clear_session" -> R.string.clear_session
        "summary_hint" -> R.string.summary_hint
        "privacy" -> R.string.privacy
        "privacy_explainer" -> R.string.privacy_explainer
        "diagnostics" -> R.string.diagnostics
        "diagnostics_explainer" -> R.string.diagnostics_explainer
        "about" -> R.string.about
        "accuracy_explainer" -> R.string.accuracy_explainer
        "filter_explainer" -> R.string.filter_explainer
        "permission_title" -> R.string.permission_title
        "permission_message" -> R.string.permission_message
        "open_settings" -> R.string.open_settings
        "error_microphone" -> R.string.error_microphone
        "interrupted" -> R.string.interrupted
        "route_changed" -> R.string.route_changed
        "background_stopped" -> R.string.background_stopped
        "limit_reached" -> R.string.limit_reached
        "clipping" -> R.string.clipping
        "invalid_signal" -> R.string.invalid_signal
        "calibration_saved" -> R.string.calibration_saved
        "keep_awake" -> R.string.keep_awake
        "keep_awake_explainer" -> R.string.keep_awake_explainer
        "locale" -> R.string.locale
        "locale_hint" -> R.string.locale_hint
        "not_configured" -> R.string.not_configured
        "sample_data" -> R.string.sample_data
        "sample_hint" -> R.string.sample_hint
        "version" -> R.string.version
        "delete_confirm" -> R.string.delete_confirm
        "error_export" -> R.string.error_export
        "reference_unit_hint" -> R.string.reference_unit_hint
        "reset_confirm" -> R.string.reset_confirm
        "permission_denied" -> R.string.permission_denied
        "clipped_total" -> R.string.clipped_total
        "cancel" -> R.string.cancel
        "microphone_usage" -> R.string.microphone_usage
        "stopping" -> R.string.stopping
        "licenses" -> R.string.licenses
        else -> error("Unknown UI string: $key")
    }
}
