"""Generate native Android and Apple resources from the shared copy catalog."""
from pathlib import Path
import json
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
messages = json.loads((ROOT / "localization/messages.json").read_text())
languages = list(messages["app_name"])
qualifiers = {"en": "values", "zh-Hans": "values-zh-rCN", "zh-Hant": "values-zh-rTW", "pt-BR": "values-pt-rBR"}
for key, translations in messages.items():
    if set(translations) != set(languages):
        raise SystemExit(f"Missing translations for {key}: {set(languages) - set(translations)}")
for language in languages:
    folder = ROOT / "android/app/src/main/res" / qualifiers.get(language, "values-" + language)
    folder.mkdir(parents=True, exist_ok=True)
    lines = ['<?xml version="1.0" encoding="utf-8"?>', '<resources>']
    for key, translations in messages.items():
        value = escape(translations[language]).replace("'", "\\'").replace('"', '\\"').replace('\n', '\\n')
        lines.append(f'    <string name="{key}">{value}</string>')
    lines.append('</resources>')
    (folder / "strings.xml").write_text('\n'.join(lines) + '\n')
    apple = ROOT / "ios/dm" / (language + ".lproj")
    apple.mkdir(parents=True, exist_ok=True)
    entries = {"CFBundleDisplayName": messages["app_name"][language], "NSMicrophoneUsageDescription": messages["microphone_usage"][language]}
    (apple / "InfoPlist.strings").write_text('\n'.join(json.dumps(k) + ' = ' + json.dumps(v, ensure_ascii=False) + ';' for k, v in entries.items()) + '\n')
catalog = {"sourceLanguage": "en", "strings": {}, "version": "1.0"}
for key, translations in messages.items():
    catalog["strings"][key] = {"extractionState": "manual", "localizations": {
        lang: {"stringUnit": {"state": "translated", "value": value}} for lang, value in translations.items()
    }}
(ROOT / "ios/dm/Localizable.xcstrings").write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + '\n')
locale_xml = ['<?xml version="1.0" encoding="utf-8"?>', '<locale-config xmlns:android="http://schemas.android.com/apk/res/android">']
locale_xml += [f'    <locale android:name="{lang}" />' for lang in languages]
locale_xml.append('</locale-config>')
(ROOT / "android/app/src/main/res/xml/locales_config.xml").write_text('\n'.join(locale_xml) + '\n')
print(f"Generated {len(messages)} strings for {len(languages)} languages on both platforms.")

# Typed Android IDs retain compile-time resource validation without reflection.
ids = ["// Generated by scripts/generate_localizations.py. Do not edit by hand.", "package com.izowooi.dm", "", "import androidx.annotation.StringRes", "", "object TextResources {", "    @StringRes fun id(key: String): Int = when (key) {"]
ids += [f'        "{key}" -> R.string.{key}' for key in messages]
ids += ['        else -> error("Unknown UI string: $key")', "    }", "}"]
(ROOT / "android/app/src/main/java/com/izowooi/dm/TextResources.kt").write_text("\n".join(ids) + "\n")
